version: '3.8'

services:
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    hostname: front-end
    restart: always
    cap_drop:
      - all
    read_only: true
    ports:
      - "8079:8079"
    networks:
      - sock-shop

  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    networks:
      - sock-shop
    depends_on:
      - catalogue-db

  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-fake_password}
      - MYSQL_DATABASE=socks
    networks:
      - sock-shop

  carts:
    image: weaveworksdemos/carts:0.4.8
    hostname: carts
    restart: always
    cap_drop:
      - all
    networks:
      - sock-shop
    depends_on:
      - carts-db

  carts-db:
    image: mongo:4.2
    hostname: carts-db
    restart: always
    networks:
      - sock-shop

  orders:
    image: weaveworksdemos/orders:0.4.7
    hostname: orders
    restart: always
    cap_drop:
      - all
    networks:
      - sock-shop
    depends_on:
      - orders-db
      - rabbitmq

  orders-db:
    image: mongo:4.2
    hostname: orders-db
    restart: always
    networks:
      - sock-shop

  payment:
    image: weaveworksdemos/payment:0.4.3
    hostname: payment
    restart: always
    cap_drop:
      - all
    networks:
      - sock-shop

  shipping:
    image: weaveworksdemos/shipping:0.4.8
    hostname: shipping
    restart: always
    cap_drop:
      - all
    networks:
      - sock-shop
    depends_on:
      - rabbitmq

  user:
    image: weaveworksdemos/user:0.4.7
    hostname: user
    restart: always
    cap_drop:
      - all
    networks:
      - sock-shop
    depends_on:
      - user-db

  user-db:
    image: weaveworksdemos/user-db:0.4.0
    hostname: user-db
    restart: always
    networks:
      - sock-shop

  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    hostname: queue-master
    restart: always
    networks:
      - sock-shop
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    restart: always
    networks:
      - sock-shop

networks:
  sock-shop:
    driver: bridge
