global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'front-end'
    static_configs:
      - targets: ['front-end:8079']

  - job_name: 'catalogue'
    static_configs:
      - targets: ['catalogue:80']

  - job_name: 'orders'
    static_configs:
      - targets: ['orders:80']

  - job_name: 'payment'
    static_configs:
      - targets: ['payment:80']

  - job_name: 'user'
    static_configs:
      - targets: ['user:80']
